@app_url = localhost:50051/api/app/users

### Create user
# POST {{app_url}}/create-user
# Content-Type: application/json
#
# {}


### login 
POST {{app_url}}/login
Content-Type: application/json

{
  "username":"test_username",
  "password":"123"
}

### register 
POST {{app_url}}/register
Content-Type: application/json

{
  "username":"test_username_1",
  "password":"123",
  "email":"12322"
}

### Change password 
PUT {{app_url}}/change-password
Content-Type: application/json

{
  "password":"123"
}


