@app_url = localhost:50051/api/app/users

### login 
POST {{app_url}}/login
Content-Type: application/json

{
  "username":"test_username_1",
  "password":"123"
}

### register 
POST {{app_url}}/register
Content-Type: application/json

{
  "username":"admin",
  "password":"admin",
  "email":"supervisor@email.com"
}

### Change password 
PUT {{app_url}}/change-password
Content-Type: application/json

{
  "username":"test_username_1",
  "password":"123"
}

### Change password 
POST {{app_url}}/create-post
Content-Type: application/json

{
  "author": 1,
  "subAuthor": 2
}


